# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.anime:
        class: AnimeBundle\Admin\AnimeAdmin
        arguments: [~, AnimeBundle\Entity\Anime, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Animes }
    admin.animeType:
        class: AnimeBundle\Admin\AnimeTypeAdmin
        arguments: [~, AnimeBundle\Entity\AnimeType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Anime Types }
    admin.animeGenre:
        class: AnimeBundle\Admin\AnimeGenreAdmin
        arguments: [~, AnimeBundle\Entity\AnimeGenre, ~]
        tags:
             - { name: sonata.admin, manager_type: orm, label: Anime Genres }
    admin.user:
        class: AnimeBundle\Admin\UserAdmin
        arguments: [~, AnimeBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users }
    admin.episode:
        class: AnimeBundle\Admin\EpisodeAdmin
        arguments: [~, AnimeBundle\Entity\Episode, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Episodes }
    admin.animeScore:
        class: AnimeBundle\Admin\AnimeScoreAdmin
        arguments: [~, AnimeBundle\Entity\AnimeScore, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Animes Scores }
    admin.episodeScore:
        class: AnimeBundle\Admin\EpisodeScoreAdmin
        arguments: [~, AnimeBundle\Entity\EpisodeScore, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Episodes Scores }
    admin.animeReview:
        class: AnimeBundle\Admin\AnimeReviewAdmin
        arguments: [~, AnimeBundle\Entity\AnimeReview, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Animes Reviews }
    admin.episodeReview:
        class: AnimeBundle\Admin\EpisodeReviewAdmin
        arguments: [~, AnimeBundle\Entity\EpisodeReview, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Episodes Reviews }
    admin.userHasAnimes:
        class: AnimeBundle\Admin\UserHasAnimesAdmin
        arguments: [~, AnimeBundle\Entity\UserHasAnimes, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User Has Animes }
    admin.userHasEpisodes:
        class: AnimeBundle\Admin\UserHasEpisodesAdmin
        arguments: [~, AnimeBundle\Entity\UserHasEpisodes, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User Has Episodes }