<?php

namespace AnimeBundle\Repository;

/**
 * AnimeScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
