<?php

namespace AnimeBundle\Repository;

/**
 * AnimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function findById($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AnimeBundle:Anime p WHERE p.id = :id')
            ->setParameter('id', $id)
            ->getResult();
    }

    /**
     * @param $genreid
     * @return array
     */
    public function findByGenre($genreid)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AnimeBundle:Anime p WHERE p.genre = :genreid')
            ->setParameter('genreid', $genreid)
            ->getResult();
    }
}
