<?php

namespace AnimeBundle\Repository;

/**
 * AnimeScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeScoreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $animeId
     * @return mixed
     */
    public function getAverageById($animeId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT AVG(p.value) FROM AnimeBundle:AnimeScore p WHERE p.anime = :id')
            ->setParameter('id', $animeId)
            ->getSingleScalarResult();
    }

    /**
     * @return array
     */
    public function getScoreRanking()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT AVG(p.value) as score, partial a.{id, name} FROM AnimeBundle:AnimeScore p JOIN AnimeBundle:Anime AS a WITH p.anime = a GROUP BY p.anime ORDER BY score DESC')
            ->setMaxResults(3)
            ->getResult();
    }
}
