<?php

namespace AnimeBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllById($id)  {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AnimeBundle:Episode p WHERE p.anime = :id ORDER BY p.aired ASC'  )
            ->setParameter('id', $id)
            ->getResult();
    }
}
