<?php

namespace AnimeBundle\Repository;

/**
 * EpisodeReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
