<?php

namespace AnimeBundle\Repository;

/**
 * UserHasAnimesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasAnimesRepository extends \Doctrine\ORM\EntityRepository
{
}
