<?php

namespace AnimeBundle\Repository;

/**
 * UserHasAnimesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasAnimesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $animeId
     * @return mixed
     */
    public function getFollowersById($animeId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p) FROM AnimeBundle:UserHasAnimes p WHERE p.anime = :id')
            ->setParameter('id', $animeId)
            ->getSingleScalarResult();
    }

    /**
     * @param $animeId
     * @return mixed
     */
    public function getFavorisById($animeId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p) FROM AnimeBundle:UserHasAnimes p WHERE p.anime = :id AND p.favori = 1')
            ->setParameter('id', $animeId)
            ->getSingleScalarResult();
    }

    /**
     * @param $animeId
     * @param $user
     * @return array
     */
    public function findByAnimeAndUserId($animeId, $user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AnimeBundle:UserHasAnimes p WHERE p.anime = :id AND p.user = :user')
            ->setParameter('id', $animeId)
            ->setParameter('user', $user)
            ->getResult();
    }

    /**
     * @return array
     */
    /*public function getFollowersRanking()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT count(p) AS p.followers, p.anime FROM AnimeBundle:UserHasAnimes p GROUP BY p.anime ORDER BY p.followers DESC ')
            ->getResult();
    }*/


}
