<?php

namespace AnimeBundle\Repository;

/**
 * UserHasAnimesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasAnimesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $animeId
     * @return mixed
     */
    public function getFollowersById($animeId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p) FROM AnimeBundle:UserHasAnimes p WHERE p.anime = :id')
            ->setParameter('id', $animeId)
            ->getSingleScalarResult();
    }

    /**
     * @param $animeId
     * @return mixed
     */
    public function getFavorisById($animeId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p) FROM AnimeBundle:UserHasAnimes p WHERE p.anime = :id AND p.favori = 1')
            ->setParameter('id', $animeId)
            ->getSingleScalarResult();
    }

    /**
     * @param $animeId
     * @param $user
     * @return array
     */
    public function findByAnimeAndUserId($animeId, $user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AnimeBundle:UserHasAnimes p WHERE p.anime = :id AND p.user = :user')
            ->setParameter('id', $animeId)
            ->setParameter('user', $user)
            ->getResult();
    }

    /**
    * @return array
    */
    public function getFollowersRanking()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p.id) as followers, partial a.{id, name} FROM AnimeBundle:UserHasAnimes p JOIN AnimeBundle:Anime AS a WITH p.anime = a GROUP BY p.anime ORDER BY followers DESC ')
            ->setMaxResults(3)
            ->getResult();
    }

    /**
     *
     * @return array
     */
    public function getFavorisRanking()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(p.id) as followers, partial a.{id, name} FROM AnimeBundle:UserHasAnimes p JOIN AnimeBundle:Anime AS a WITH p.anime = a WHERE p.favori = 1 GROUP BY p.anime ORDER BY followers DESC ')
            ->setMaxResults(3)
            ->getResult();
    }

}
